name: Automatically Deploy Hexo Blog 
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

      
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest 
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@v2

    # from: https://github.com/actions/setup-node  
    # - name: Setup Node.js 14.x 
    #   uses: actions/setup-node@master
    #   with:
    #     node-version: "14.x"
    
    - name: Setup Git Infomation
      run: |-
        git config --global user.name "${{ secrets.GIT_USER }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"

    - name: Setup Deploy Private Key
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # 此处会即时构建 nodejs 的 docker 环境，安装 npm modules
    - name: Init Hexo Environment
      run: |
        ./init.sh -e "${{ secrets.GIT_EMAIL }}" -u "${{ secrets.GIT_USER }}" -n "${{ secrets.DEPLOY_REPO_NAME }}" -d "${{ secrets.BLOG_DOMAIN }}"

    - name: Build And Deploy Hexo 
      run: |
        ./build.sh -e prod

